name: PixelsKenya
favicon: null
layout_spectrum: 0.6212
typography_spectrum: 0.48045
title: PixelsKenya
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#913779'
    - '#000000'
    - '#e2d437'
    - '#209fd9'
    - '#ff0000'
  brandStrength: 0
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
