name: PixelsKenya
favicon: null
layout_spectrum: 0.5198574122041464
typography_spectrum: 0.27584845875389874
title: PixelsKenya
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7225495376624167
  lightness: 0.22279831115156412
  saturation: 0.30854516942054033
  rhythmicContrast: 0.8804188286885619
purpose: []
